export { default as Client } from "./client";

export type {
  UserAccountBirthdate,
  UserAccountDescription,
  UserAccountGender,
  UserAccountMetaData,
  UserAccountOwnPromotionChannels,
  UserAccountPromotionChannels,
  UserAccountRobloxBadge,
  UserAccountRobloxBadges,
  UserAccountSetStarCodeAffiliate,
  UserAccountStarCodeAffiliate,
  UserAccountXboxConsecutiveLoginDays
} from "./client/apis/AccountInformationAPI";
export type {
  AccountSettingsAppChatPrivacy,
  AccountSettingsBlockUser,
  AccountSettingsGameChatPrivacy,
  AccountSettingsGroup,
  AccountSettingsGroups,
  AccountSettingsInventoryPrivacy,
  AccountSettingsMetaData,
  AccountSettingsPrivacy,
  AccountSettingsPrivacyInfo,
  AccountSettingsPrivateMessagePrivacy,
  AccountSettingsVisibilityPrivacy
} from "./client/apis/AccountSettingsAPI";
export type {
  AdConfigurationCreateSponsoredGameAd,
  AdConfigurationSponsoredGame,
  AdConfigurationSponsoredGames,
  AdConfigurationStopSponsoredGameAd,
  AdConfigurationTargetAgeBracket,
  AdConfigurationTargetDeviceType,
  AdConfigurationTargetGender,
  AdConfigurationUniverse,
  AdConfigurationUniverses
} from "./client/apis/AdConfigurationAPI";
export type {
  BaseAsset,
  BaseAssetDeliveryOptions,
  BaseAssetRaw,
  GetAssetByAlias,
  GetAssetByAliasOptions,
  GetAssetByAssetId,
  GetAssetByAssetIdOptions,
  GetAssetByAssetVersionId,
  GetAssetByAssetVersionIdOptions,
  GetAssetByHash,
  GetAssetByHashOptions,
  GetAssetById,
  GetAssetByIdOptions,
  GetAssetByMarAssetHash,
  GetAssetByMarAssetHashOptions,
  GetAssetByUserAssetId,
  GetAssetByUserAssetIdOptions,
  GetAssetVersionByAssetId,
  GetAssetVersionByAssetIdOptions,
  GetBatchAssets,
  GetBatchAssetsOptions
} from "./client/apis/AssetDeliveryAPI";
export type {
  ChangeUserPassword,
  ChangeUserPasswordOptions,
  ChangeUsername,
  ChangeUsernameOptions,
  GetAuthMetaData,
  AuthMetaData,
  AuthPin,
  AuthTicket,
  GetCredentialsVerificationStatus,
  GetCredentialsVerificationStatusOptions,
  GetCurrentPasswordStatus,
  GetExistingUsernames,
  GetExistingUsernamesOptions,
  GetMetaData as GetAuthAPIMetaData,
  GetPasswordResetMetaData,
  GetPasswordResetMetaDataOptions,
  GetRecoveryMetaData,
  GetSAMLMetaData,
  GetTwoStepVerificationMetaData as GetAuthTwoStepVerificationMetaData,
  Login,
  LoginOptions,
  Logout,
  RecoverUsernames,
  RecoverUsernamesOptions,
  RequestTwoStepVerification,
  ResendTwoStepVerification,
  ResendTwoStepVerificationOptions,
  ResetPassword,
  ResetPasswordOptions,
  RevertAccount,
  RevertAccountInfo,
  RevertAccountInfoOptions,
  RevertAccountOptions,
  SAMLRequest,
  SendCredentialsVerificationMessage,
  SendCredentialsVerificationMessageOptions,
  SendPasswordReset,
  SendPasswordResetOptions,
  SignUp,
  SignUpOptions,
  ValidatePassword,
  ValidatePasswordOptions,
  ValidateUsername,
  ValidateUsernameOptions,
  VerifyPasswordReset,
  VerifyPasswordResetOptions,
  VerifyTwoStepVerification,
  VerifyTwoStepVerificationOptions
} from "./client/apis/AuthAPI";
export type {
  BodyColors,
  BodyScales,
  ColorPalette,
  CreateOutfit,
  CreateOutfitOptions,
  DeleteOutfit,
  DeleteOutfitOptions,
  GetAvatarMetadata,
  GetAvatarRules,
  GetOutfit,
  GetOutfitOptions,
  GetRecentItems,
  GetRecentItemsOptions,
  GetUserAvatar,
  GetUserAvatarOptions,
  GetUserCurrentlyWearing,
  GetUserCurrentlyWearingOptions,
  GetUserOutfits,
  GetUserOutfitsOptions,
  RedrawThumbnail,
  RemoveAssetFromAvatar,
  RemoveAssetFromAvatarOptions,
  Scale,
  SetBodyColors,
  SetBodyColorsOptions,
  SetPlayerAvatarScales,
  SetPlayerAvatarScalesOptions,
  SetPlayerAvatarType,
  SetPlayerAvatarTypeOptions,
  SetPlayerAvatarWearingAssets,
  SetPlayerAvatarWearingAssetsOptions,
  UpdateOutfit,
  UpdateOutfitOptions,
  UserAvatar,
  WearAssetOnAvatar,
  WearAssetOnAvatarOptions,
  WearOutfit,
  WearOutfitOptions
} from "./client/apis/AvatarAPI";
export type {
  DeleteBadgeFromSelf,
  DeleteBadgeFromSelfOptions,
  DeleteBadgeFromUser,
  DeleteBadgeFromUserOptions,
  GetBadge,
  GetBadgeOptions,
  GetUniverseBadges,
  GetUniverseBadgesOptions,
  GetUserBadges,
  GetUserBadgesAwardedDates,
  GetUserBadgesAwardedDatesOptions,
  GetUserBadgesOptions,
  UpdateBadge,
  UpdateBadgeOptions
} from "./client/apis/BadgesAPI";
export type { BaseAPIRequestOptions } from "./client/apis/BaseAPI";
export type {
  GetDeveloperExchangeRate,
  GetLatestLuobuDeveloperExchangeStatus,
  GetLuobuDeveloperExchangeBalance,
  GetLuobuDeveloperExchangeEligibility,
  GetUserPayments,
  GetUserPaymentsOptions,
  GetXsollaIFrameToken,
  GetXsollaIFrameTokenOptions,
  IncrementCounterByAgent,
  IncrementCounterByAgentOptions,
  PurchaseAmazonProduct,
  PurchaseAmazonProductOptions,
  PurchaseAppleProduct,
  PurchaseAppleProductOptions,
  PurchaseGoogleProduct,
  PurchaseGoogleProductOptions,
  RedeemDigitalCode,
  RedeemDigitalCodeOptions,
  RedeemGameCard,
  RedeemGameCardOptions,
  RedeemPromoCode,
  RedeemPromoCodeOptions,
  ReverseGameCard,
  ReverseGameCardOptions,
  SendXsollaWebhook,
  SendXsollaWebhookOptions,
  SubmitLuobuDeveloperExchange,
  SubmitLuobuDeveloperExchangeOptions,
  ValidateAmazonProduct,
  ValidateAmazonProductOptions,
  ValidateAppleProduct,
  ValidateAppleProductOptions,
  ValidateGoogleProduct,
  ValidateGoogleProductOptions
} from "./client/apis/BillingAPI";
export type {
  FavoriteAsset,
  FavoriteAssetOptions,
  FavoriteBundle,
  FavoriteBundleOptions,
  GetAppStoreExclusiveBundles,
  GetAppStoreExclusiveBundlesOptions,
  GetAssetBundles,
  GetAssetBundlesOptions,
  GetAssetFavoriteCount,
  GetAssetFavoriteCountOptions,
  GetAssetToCategory,
  GetAssetToSubCategory,
  GetBundleDetails,
  GetBundleDetailsOptions,
  GetBundleFavoriteCount,
  GetBundleFavoriteCountOptions,
  GetBundleRecommendationsByBundleId,
  GetBundleRecommendationsByBundleIdOptions,
  GetCategories,
  GetMultiBundleDetails,
  GetMultiBundleDetailsOptions,
  GetSelfFavoriteBundle,
  GetSelfFavoriteBundleOptions,
  GetSubCategories,
  GetUserBundles,
  GetUserBundlesByType,
  GetUserBundlesByTypeOptions,
  GetUserBundlesOptions,
  GetUserFavoriteAsset,
  GetUserFavoriteAssetOptions,
  ProductDetails,
  RemoveFavoriteBundle,
  RemoveFavoriteBundleOptions,
  RemoveSelfAssetFavorite,
  RemoveSelfAssetFavoriteOptions,
  UnpackBundle,
  UnpackBundleOptions
} from "./client/apis/CatalogAPI";
export type {
  AddUsersToConversation,
  AddUsersToConversationOptions,
  GetChatSettings,
  GetConversationMessages,
  GetConversationMessagesOptions,
  GetConversations,
  GetConversationsOptions,
  GetMetaData as GetChatAPIMetaData,
  GetMultiLatestConversationMessages,
  GetMultiLatestConversationMessagesOptions,
  GetRolloutSettings,
  GetRolloutSettingsOptions,
  GetUnreadConversationCount,
  GetUnreadMessagesInConversations,
  GetUnreadMessagesInConversationsOptions,
  GetUserConversations,
  GetUserConversationsOptions,
  MarkConversationsAsSeen,
  MarkConversationsAsSeenOptions,
  MarkMessageInConversationAsRead,
  MarkMessageInConversationAsReadOptions,
  RemoveUserFromConversation,
  RemoveUserFromConversationOptions,
  RenameGroupConversation,
  RenameGroupConversationOptions,
  ResetConversationUniverse,
  ResetConversationUniverseOptions,
  SendGameLinkMessage,
  SendGameLinkMessageOptions,
  SendMessage as SendChatMessage,
  SendMessageOptions as SendChatMessageOptions,
  SetConversationUniverse,
  SetConversationUniverseOptions,
  StartCloudEditConversation,
  StartCloudEditConversationOptions,
  StartGroupConversation,
  StartGroupConversationOptions,
  StartOneToOneConversation,
  StartOneToOneConversationOptions,
  UpdateUserTypingStatus,
  UpdateUserTypingStatusOptions
} from "./client/apis/ChatAPI";
export type {
  GetContactsMetaData,
  GetUsersTags,
  GetUsersTagsOptions,
  SetPendingUserTag,
  SetPendingUserTagOptions,
  SetUserTag,
  SetUserTagOptions
} from "./client/apis/ContactsAPI";
export type {
  UploadDataOptions,
  UploadDataResult
} from "./client/apis/DataAPI";
export type {
  ActivateUniverse,
  ActivateUniverseOptions,
  CreateDeveloperProduct,
  CreateDeveloperProductOptions,
  CreateUniverseAlias,
  CreateUniverseAliasOptions,
  DeactivateUniverse,
  DeactivateUniverseOptions,
  DeleteUniverseAlias,
  DeleteUniverseAliasOptions,
  DownloadUniverseStatisticsReportByTime,
  DownloadUniverseStatisticsReportByTimeOptions,
  FilterPublishGameNotification,
  FilterPublishGameNotificationOptions,
  GenerateUniverseStatisticReportsByTime,
  GenerateUniverseStatisticReportsByTimeOptions,
  GetAssetsVoteInformation,
  GetAssetsVoteInformationOptions,
  GetGameTemplates,
  GetGameUpdatesHistory,
  GetGameUpdatesHistoryOptions,
  GetGroupUniverses,
  GetGroupUniversesOptions,
  GetNotificationsStatisticReports,
  GetPlaceCompatibilities,
  GetPlaceCompatibilitiesOptions,
  GetPlaceStatisticsByType,
  GetPlaceStatisticsByTypeOptions,
  GetPluginsById,
  GetPluginsByIdOptions,
  GetSelfGroupsAccess,
  GetSelfTeamCreateUniversesAccess,
  GetSelfTeamCreateUniversesAccessOptions,
  GetSelfUniverses,
  GetSelfUniversesOptions,
  GetStudioData,
  GetStudioDataOptions,
  GetUniverse,
  GetUniverseConfiguration,
  GetUniverseConfigurationOptions,
  GetUniverseOptions,
  GetUniversePermissions,
  GetUniversePermissionsOptions,
  GetUniversePlaces,
  GetUniversePlacesOptions,
  GetUniverseStatisticsReportByTime,
  GetUniverseStatisticsReports,
  GetUniverseStatisticsReportsByTimeOptions,
  GetUniverseStatisticsReportsOptions,
  GetUniverseTeamCreateSettings,
  GetUniverseTeamCreateSettingsOptions,
  GetUniverseVIPServersConfiguration,
  GetUniverseVIPServersConfigurationOptions,
  GetUsersInUniverseTeamCreate,
  GetUsersInUniverseTeamCreateOptions,
  MultiGetUniverses,
  MultiGetUniversesOptions,
  MultiGetUniversesPermissions,
  MultiGetUniversesPermissionsOptions,
  PublishGameNotification,
  PublishGameNotificationOptions,
  RemoveUserFromUniverseTeamCreate,
  RemoveUserFromUniverseTeamCreateOptions,
  SearchToolbox,
  SearchToolboxOptions,
  SearchUniverseData,
  SearchUniverses,
  SearchUniversesOptions,
  SetStudioData,
  SetStudioDataOptions,
  UpdateDeveloperProduct,
  UpdateDeveloperProductOptions,
  UpdatePlaceConfiguration,
  UpdatePlaceConfigurationOptions,
  UpdatePlugin,
  UpdatePluginOptions,
  UpdateUniverseAlias,
  UpdateUniverseAliasOptions,
  UpdateUniverseConfiguration,
  UpdateUniverseConfigurationOptions,
  UpdateUniverseTeamCreateSettings,
  UpdateUniverseTeamCreateSettingsOptions
} from "./client/apis/DevelopAPI";
export type {
  GetAssetResaleData,
  GetAssetResaleDataOptions,
  GetAssetResellers,
  GetAssetResellersOptions,
  GetDeveloperExchangeAbility,
  GetDeveloperExchangeHelp,
  GetDeveloperExchangeInfo,
  GetDeveloperExchangeInfoOptions,
  GetGroupCurrency,
  GetGroupCurrencyOptions,
  GetGroupRevenueSummaryInTimeFrame,
  GetGroupRevenueSummaryInTimeFrameOptions,
  GetGroupTransactions,
  GetGroupTransactionsOptions,
  GetResaleTaxRate,
  GetSelfCurrency,
  GetSelfCurrencyOptions,
  GetSelfRevenueSummaryInTimeFrame,
  GetSelfRevenueSummaryInTimeFrameOptions,
  GetSelfTransactions,
  GetSelfTransactionsOptions,
  GetUserResellableAssetCopies,
  GetUserResellableAssetCopiesOptions,
  SetAssetCopies,
  SetAssetCopiesOptions,
  SubmitDeveloperExchange,
  SubmitDeveloperExchangeOptions
} from "./client/apis/EconomyAPI";
export type {
  GetUniverseStats,
  GetUniverseStatsOptions
} from "./client/apis/EconomyCreatorStatsAPI";
export type {
  GetUniversePayoutHistory,
  GetUniversePayoutHistoryOptions
} from "./client/apis/EngagementPayoutsAPI";
export type {
  FollowUniverse,
  FollowUniverseOptions,
  GetUserFollowedUniverses,
  GetUserFollowedUniversesOptions,
  GetUserFollowingUniverseStatus,
  GetUserFollowingUniverseStatusOptions,
  UnFollowUniverse,
  UnFollowUniverseOptions
} from "./client/apis/FollowingsAPI";
export type {
  CheckSessionHealth,
  DeclineAllFriendRequests,
  DeleteQRCodeSession,
  DeleteSession,
  FindFriendByCode,
  FindFriendByCodeOptions,
  FollowUser as FriendsAPIFollowUser,
  FollowUserOptions as FriendsAPIFollowUserOptions,
  GetMetaData,
  GetMetaDataOptions,
  GetOrCreateNearbySession,
  GetOrCreateQRCodeSession,
  GetSelfFriendRequests,
  GetSelfFriendRequestsCount,
  GetSelfFriendRequestsOptions,
  GetSelfFriendsCount,
  GetSelfRecommendedUsers,
  GetUserFollowers,
  GetUserFollowersCount,
  GetUserFollowersCountOptions,
  GetUserFollowersOptions,
  GetUserFollowing,
  GetUserFollowingCount,
  GetUserFollowingCountOptions,
  GetUserFollowingOptions,
  GetUserFriends as FriendsAPIGetUserFriends,
  GetUserFriendsOptions as FriendsAPIGetUserFriendsOptions,
  GetUserFriendsWithStatuses,
  GetUserFriendsWithStatusesOptions,
  GetUserOnlineFriends,
  GetUserOnlineFriendsOptions,
  RedeemNearbyFriendCode,
  RedeemNearbyFriendCodeOptions,
  RedeemQRCode,
  RedeemQRCodeOptions,
  SendFriendRequest as FriendsAPISendFriendRequest,
  SendFriendRequestOptions as FriendsAPISendFriendRequestOptions,
  UnFollowUser,
  UnFollowUserOptions,
  UnfriendUser as FriendsAPIUnfriendUser,
  UnfriendUserOptions as FriendsAPIUnfriendUserOptions
} from "./client/apis/FriendsAPI";
export type {
  GetGameAutomaticTranslationResults,
  GetGameAutomaticTranslationResultsOptions,
  GetGameInfo,
  GetGameInfoHistory,
  GetGameInfoHistoryOptions,
  GetGameInfoOptions,
  GetGameSourceLanguage,
  GetGameSourceLanguageOptions,
  GetGameSupportedLanguages,
  GetGameSupportedLanguagesOptions,
  GetNameDescriptionMetaData,
  GetSupportedLanguagesMetaData,
  ModifyGameSupportedLanguages,
  ModifyGameSupportedLanguagesOptions,
  ToggleAutomaticGameTranslation,
  ToggleAutomaticGameTranslationOptions,
  UpdateGameInfo,
  UpdateGameInfoOptions,
  UpdateGameSourceLanguage,
  UpdateGameSourceLanguageOptions
} from "./client/apis/GameInternationalizationAPI";
export type {
  CanSelfInviteUserToVIPServer,
  CanSelfInviteUserToVIPServerOptions,
  CreateVIPServer,
  CreateVIPServerOptions,
  GameGamesProductInfo,
  GameServer,
  GetGameFavoriteCount,
  GetGameFavoriteCountOptions,
  GetGameGamePasses,
  GetGameGamePassesOptions,
  GetGameRecommendationsByAlgorithm,
  GetGameRecommendationsByAlgorithmOptions,
  GetGameRecommendationsByGame,
  GetGameRecommendationsByGameOptions,
  GetGameServersByType,
  GetGameServersByTypeOptions,
  GetGameSorts,
  GetGameSortsOptions,
  GetGameUniverses,
  GetGameUniversesOptions,
  GetGamesProductInfoOptions,
  GetGamesVotes,
  GetGamesVotesOptions,
  GetSelfUniverseVoteStatus,
  GetSelfUniverseVoteStatusOptions,
  GetVIPServer,
  GetVIPServerOptions,
  IsGameFavorited,
  IsGameFavoritedOptions,
  ListGames,
  ListGamesOptions,
  MultiGetGameUniversesPlayability,
  MultiGetGameUniversesPlayabilityOptions,
  MultiGetPlaces,
  MultiGetPlacesOptions,
  SetSelfGameVote,
  SetSelfGameVoteOptions,
  ToggleGameFavorite,
  ToggleGameFavoriteOptions,
  UpdateVIPServer,
  UpdateVIPServerOptions,
  UpdateVIPServerPermissions,
  UpdateVIPServerPermissionsOptions,
  UpdateVIPServerSubscription,
  UpdateVIPServerSubscriptionOptions
} from "./client/apis/GamesAPI";
export type {
  AcceptFriendRequest,
  AcceptFriendRequestOptions,
  AwardBadge,
  AwardBadgeOptions,
  BlockUser,
  BlockUserOptions,
  DeclineFriendRequest,
  DeclineFriendRequestOptions,
  FollowUser,
  FollowUserOptions,
  GetAssetVersionOptions,
  GetAssetVersions,
  GetBalance,
  GetDeviceInfo,
  GetGamePassProductInfo,
  GetGamePassProductInfoOptions,
  GetGroup as GeneralAPIGetGroup,
  GetGroupAllies,
  GetGroupAlliesOptions,
  GetGroupEnemies,
  GetGroupEnemiesOptions,
  GetGroupOptions as GeneralAPIGetGroupOptions,
  GetIncomingItems,
  GetProductInfo,
  GetProductInfoOptions,
  GetUserById as GeneralAPIGetUserById,
  GetUserByIdOptions as GeneralAPIGetUserByIdOptions,
  GetUserByUsername,
  GetUserByUsernameOptions,
  GetUserFriends,
  GetUserFriendsCount,
  GetUserFriendsCountOptions,
  GetUserFriendsOptions,
  GetUserGroups as GeneralAPIGetUserGroups,
  GetUserGroupsOptions as GeneralAPIGetUserGroupsOptions,
  IsUserFollowing,
  IsUserFollowingOptions,
  SendFriendRequest,
  SendFriendRequestOptions,
  UnblockUser,
  UnblockUserOptions,
  UnfollowUser,
  UnfollowUserOptions,
  UnfriendUser,
  UnfriendUserOptions,
  UserCanManageAsset,
  UserCanManageAssetOptions,
  UserOwnsAsset,
  UserOwnsAssetOptions
} from "./client/apis/GeneralAPI";
export type {
  AcceptJoinRequest,
  AcceptJoinRequestOptions,
  AcceptJoinRequests,
  AcceptJoinRequestsOptions,
  AcceptRelationshipRequest,
  AcceptRelationshipRequestOptions,
  AcceptRelationshipRequests,
  AcceptRelationshipRequestsOptions,
  ChangeOwner,
  ChangeOwnerOptions,
  ClaimGroup,
  ClaimGroupOptions,
  CreateGroup,
  CreateGroupOptions,
  CreateRelationship,
  CreateRelationshipOptions,
  CreateRole,
  CreateRoleOptions,
  CreateWallPost,
  CreateWallPostOptions,
  DeclineJoinRequest,
  DeclineJoinRequestOptions,
  DeclineJoinRequests,
  DeclineJoinRequestsOptions,
  DeclineRelationshipRequest,
  DeclineRelationshipRequestOptions,
  DeclineRelationshipRequests,
  DeclineRelationshipRequestsOptions,
  DeleteRelationship,
  DeleteRelationshipOptions,
  DeleteRole,
  DeleteRoleOptions,
  DeleteSocialLink,
  DeleteSocialLinkOptions,
  DeleteWallPost,
  DeleteWallPostOptions,
  DeleteWallPostsByUser,
  DeleteWallPostsByUserOptions,
  GetAllRolesPermissions,
  GetAllRolesPermissionsOptions,
  GetGroup,
  GetGroupAuditLogs,
  GetGroupAuditLogsOptions,
  GetGroupConfigurationMetaData,
  GetGroupOptions,
  GetGroupPayouts,
  GetGroupPayoutsOptions,
  GetGroupRelationships,
  GetGroupRelationshipsOptions,
  GetGroupRoles,
  GetGroupRolesOptions,
  GetGroupSearchMetaData,
  GetGroupSettings,
  GetGroupSettingsOptions,
  GetGroupsMetaData,
  GetGuestPermissions,
  GetGuestPermissionsOptions,
  GetJoinRequest,
  GetJoinRequestOptions,
  GetJoinRequests,
  GetJoinRequestsOptions,
  GetMembers,
  GetMembersOptions,
  GetMembersWithRole,
  GetMembersWithRoleOptions,
  GetMultiGroups,
  GetMultiGroupsOptions,
  GetRelationshipRequests,
  GetRelationshipRequestsOptions,
  GetRolePermissions,
  GetRolePermissionsOptions,
  GetRolesByIds,
  GetRolesByIdsOptions,
  GetSelfGroupMembership,
  GetSelfGroupMembershipOptions,
  GetSelfPendingGroupJoins,
  GetSocialLinks,
  GetSocialLinksOptions,
  GetUserGroups,
  GetUserGroupsOptions,
  GetUserPrimaryGroup,
  GetUserPrimaryGroupOptions,
  GetWallPosts,
  GetWallPostsOptions,
  JoinGroup,
  JoinGroupOptions,
  KickMember,
  KickMemberOptions,
  PayoutMembers,
  PayoutMembersOptions,
  PostSocialLink,
  PostSocialLinkOptions,
  RemovePrimaryGroup,
  SearchGroups,
  SearchGroupsByKeyword,
  SearchGroupsByKeywordOptions,
  SearchGroupsOptions,
  SetPrimaryGroup,
  SetPrimaryGroupOptions,
  UpdateGroupDescription,
  UpdateGroupDescriptionOptions,
  UpdateGroupIcon,
  UpdateGroupIconOptions,
  UpdateGroupSettings,
  UpdateGroupSettingsOptions,
  UpdateGroupStatus,
  UpdateGroupStatusOptions,
  UpdateMember,
  UpdateMemberOptions,
  UpdateRecurringPayouts,
  UpdateRecurringPayoutsOptions,
  UpdateRole,
  UpdateRoleOptions,
  UpdateRolePermissions,
  UpdateRolePermissionsOptions,
  UpdateSocialLink,
  UpdateSocialLinkOptions
} from "./client/apis/GroupsAPI";
export type {
  GetAssetOwners,
  GetAssetOwnersOptions,
  GetPackageAssets,
  GetPackageAssetsOptions,
  GetUserCollectibles,
  GetUserCollectiblesOptions,
  GetUserInventory,
  GetUserInventoryByAssetTypeId,
  GetUserInventoryByAssetTypeIdOptions,
  GetUserInventoryOptions,
  GetUserItemsByTypeAndTargetId,
  GetUserItemsByTypeAndTargetIdOptions
} from "./client/apis/InventoryAPI";
export type {
  CreateItemTag,
  CreateItemTagOptions,
  DeleteItemTag,
  DeleteItemTagOptions,
  GetCreatedAssets,
  GetCreatedAssetsOptions,
  GetItemTagsByItemIds,
  GetItemTagsByItemIdsOptions,
  GetItemTagsMetaData,
  GetMultiCreatedAssetDetails,
  GetMultiCreatedAssetDetailsOptions,
  GetTagsByTagIds,
  GetTagsByTagIdsOptions,
  SearchTags,
  SearchTagsOptions
} from "./client/apis/ItemConfigurationAPI";
export type {
  GetCountryRegions,
  GetCountryRegionsOptions,
  GetLocales,
  GetLocalesOptions,
  GetLocusSupportedLocales,
  GetSupportedLocales,
  GetUserLocale,
  SetUserLocale,
  SetUserLocaleOptions
} from "./client/apis/LocaleAPI";
export type {
  GetThumbnailsMetaData,
  ReportBundleLoad as RecordBundleLoad,
  ReportBundleLoadOptions as RecordBundleLoadOptions,
  RecordThumbnailLoad,
  RecordThumbnailLoadOptions
} from "./client/apis/MetricsAPI";
export type {
  AllowNotificationSource,
  AllowNotificationSourceOptions,
  AllowNotificationsDestination,
  AllowNotificationsDestinationOptions,
  ClearUnreadStreamNotifications,
  DeregisterAllDevices,
  DeregisterCurrentDevice,
  DisallowNotificationSource,
  DisallowNotificationSourceOptions,
  DisallowNotificationsDestination,
  DisallowNotificationsDestinationOptions,
  GetChromeNotificationsManifest,
  GetCurrentNotificationDeviceDestination,
  GetLatestUniverseUpdates,
  GetLatestUniversesUpdatesOptions,
  GetNotificationDestinations,
  GetNotificationIds,
  GetNotificationIdsOptions,
  GetNotificationsMetaData,
  GetNotificationsMetaDataOptions,
  GetNotificationsSettings,
  GetRealtimeNotificationsSettings,
  GetRecentStreamNotifications,
  GetRecentStreamNotificationsOptions,
  GetStreamNotificationsMetaData,
  GetStreamNotificationsPromptSettings,
  GetStreamNotificationsUnreadCount,
  MarkNotificationCategoryRead,
  MarkNotificationCategoryReadOptions,
  MarkNotificationInteraction,
  MarkNotificationInteractionOptions,
  MarkNotificationRead,
  MarkNotificationReadOptions,
  MarkStreamNotificationInteracted,
  MarkStreamNotificationInteractedOptions,
  RegisterAmazonAndroid,
  RegisterAmazonAndroidOptions,
  RegisterAndroidNative,
  RegisterAndroidNativeOptions,
  RegisterAndroidTencentService,
  RegisterAndroidTencentServiceOptions,
  RegisterChrome,
  RegisterChromeOptions,
  RegisterFirefox,
  RegisterFirefoxOptions,
  RegisterIOSNative,
  RegisterIOSNativeOptions,
  SendGameUpdateNotificationInteracted,
  SendGameUpdateNotificationInteractedOptions,
  SendGameUpdateNotificationRead,
  SendGameUpdateNotificationReadOptions,
  SuppressStreamNotificationsPrompt,
  UpdateNotificationDestinationSettings,
  UpdateNotificationDestinationSettingsOptions,
  UpdateNotificationSettings,
  UpdateNotificationSettingsOptions
} from "./client/apis/NotificationsAPI";
export type {
  GetUserProfileHeader,
  GetUserProfileHeaderOptions
} from "./client/apis/OtherAPI";
export type {
  PremiumUpsellCheck,
  PremiumUpsellCheckOptions,
  ValidateUserMembership,
  ValidateUserMembershipOptions
} from "./client/apis/PremiumFeaturesAPI";
export type {
  GetUsersPresences,
  GetUsersPresencesOptions,
  RegisterAppPresence,
  RegisterAppPresenceOptions
} from "./client/apis/PresenceAPI";
export type {
  ArchiveMessages,
  ArchiveMessagesOptions,
  GetAnnouncements,
  GetAnnouncementsMetaData,
  GetMessage,
  GetMessageOptions,
  GetMessages,
  GetMessagesOptions,
  GetUnreadMessagesCount,
  MarkMessagesRead,
  MarkMessagesReadOptions,
  MarkMessagesUnread,
  MarkMessagesUnreadOptions,
  SendMessage,
  SendMessageOptions,
  UnArchiveMessages,
  UnArchiveMessagesOptions
} from "./client/apis/PrivateMessagesAPI";
export type {
  PublishAudio,
  PublishAudioOptions,
  PublishBadgeIcon,
  PublishBadgeIconOptions,
  PublishGamePassIcon,
  PublishGamePassIconOptions,
  UploadAssets,
  UploadAssetsOptions,
  UploadGameThumbnail,
  UploadGameThumbnailOptions,
  UploadPluginIcon,
  UploadPluginIconOptions,
  VerifyAudio,
  VerifyAudioOptions
} from "./client/apis/PublishAPI";
export type {
  GetAssetsThumbnails,
  GetAssetsThumbnailsOptions,
  GetBadgesIcons,
  GetBadgesIconsOptions,
  GetBatchImages,
  GetBatchImagesOptions,
  GetBundlesThumbnails,
  GetBundlesThumbnailsOptions,
  GetDeveloperProductsIcons,
  GetDeveloperProductsIconsOptions,
  GetGamePassesIcons,
  GetGamePassesIconsOptions,
  GetGroupsIcons,
  GetGroupsIconsOptions,
  GetUniverseThumbnails,
  GetUniverseThumbnailsOptions,
  GetUniversesRootPlaceThumbnails,
  GetUniversesRootPlaceThumbnailsOptions,
  GetUniversesThumbnails,
  GetUniversesThumbnailsOptions,
  GetUsersAvatarBustImages,
  GetUsersAvatarBustImagesOptions,
  GetUsersAvatarHeadShotsImages,
  GetUsersAvatarHeadShotsImagesOptions,
  GetUsersFullBodyAvatarImages,
  GetUsersFullBodyAvatarImagesOptions,
  GetUsersOutfitsImages,
  GetUsersOutfitsImagesOptions
} from "./client/apis/ThumbnailsAPI";
export type {
  AcceptTrade,
  AcceptTradeOptions,
  CanSelfTradeWithUser,
  CanSelfTradeWithUserOptions,
  CounterTrade,
  CounterTradeOptions,
  DeclineTrade,
  DeclineTradeOptions,
  GetTrade,
  GetTradeOptions,
  GetTradesByStatusType,
  GetTradesByStatusTypeOptions,
  GetTradesCountByStatusType,
  GetTradesCountByStatusTypeOptions,
  GetTradesMetaData,
  SendTrade,
  SendTradeOptions
} from "./client/apis/TradesAPI";
export type {
  GetGameRoleAssignees,
  GetGameRoleAssigneesOptions,
  GetSelfGameRoles,
  GetSelfGameRolesOptions,
  GetSelfGamesAccessByRole,
  GetSelfGamesAccessByRoleOptions,
  UpdateUser,
  UpdateUserAccess
} from "./client/apis/TranslationRolesAPI";
export type {
  AuthenticatorDisable,
  AuthenticatorDisableOptions,
  AuthenticatorEnable,
  AuthenticatorEnableOptions,
  AuthenticatorVerify,
  AuthenticatorVerifyOptions,
  AuthenticatorVerifySetup,
  AuthenticatorVerifySetupOptions,
  EmailDisable,
  EmailDisableOptions,
  EmailEnable,
  EmailEnableOptions,
  EmailSendCode,
  EmailSendCodeOptions,
  EmailVerify,
  EmailVerifyOptions,
  GetTwoStepConfiguration,
  GetTwoStepConfigurationOptions,
  GetTwoStepVerificationMetaData,
  GetTwoStepVerificationMetaDataOptions
} from "./client/apis/TwoStepVerificationAPI";
export type {
  GetSelfAuthenticatedUserInformation,
  GetUserById,
  GetUserByIdOptions,
  GetUserStatus,
  GetUserStatusOptions,
  GetUsersByUserIds,
  GetUsersByUserIdsOptions,
  GetUsersByUsernames,
  GetUsersByUsernamesOptions,
  SearchUsers,
  SearchUsersOptions,
  SetSelfDisplayName,
  SetSelfDisplayNameOptions,
  UpdateSelfStatus,
  UpdateSelfStatusOptions,
  ValidateDisplayNameExistingUser,
  ValidateDisplayNameExistingUserOptions,
  ValidateDisplayNameNewUser,
  ValidateDisplayNameNewUserOptions
} from "./client/apis/UsersAPI";
